[project]
name = "sqlalchemy-webinar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.15.2",
    "dotenv>=0.9.9",
    "prompt>=0.4.1",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.41",
]
