[project]
name = "drfsite"
version = "0.1.0"
description = "Add your description here"
authors = [
    {name = "Helen Dobruk", email = "elena.dobruk@yandex.ru"},
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
dev-dependencies = [
    "flake8>=7.1.2",
]
